name 'evenup-riak_browser'
version '0.0.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache 2.0'
source ''
project_page 'https://github.com/jlambert121/riak-browser'
summary 'Manages riak-browser'
dependency 'puppetlabs-stdlib'
